### ISSUE TITLE
Renogy Wanderer 10A not working

### ISSUE THREAD

**Issue by whuang0705** [sophienyaa/NodeRenogy#8]
Hi, Mick and everyone,

Thank you so much for this great program, really appreciate it.

It works on Renogy Wanderer 30A but not Renogy Wanderer 10A,  any idea/suggestion to fix it would be much appreciated.

Have a nice day.

Regards,
Wade H.

**Comment by sophienyaa** [comment]
Hi Wade, without having the hardware it would be difficult for me to work out what the issue is here.

**Comment by duganj** [comment]
n=1, but my Wanderer 10A unit I was able to get working without issue. Model: RNG-CTRL-WND10. Purchased from Amazon, April 2022.

**Comment by whuang0705** [comment]
@duganj, thanks for the information, much appreciate.  I get it working now by changing my renogy wanderer 10A slave modbus address to 1 via linux modbus client.

Regard,
Wade
